# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 800)
        MainWindow.setMinimumSize(QtCore.QSize(360, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.nameTrackLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameTrackLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nameTrackLabel.setText("")
        self.nameTrackLabel.setObjectName("nameTrackLabel")
        self.gridLayout.addWidget(self.nameTrackLabel, 2, 0, 1, 1)
        self.lyricsTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.lyricsTextEdit.setReadOnly(True)
        self.lyricsTextEdit.setObjectName("lyricsTextEdit")
        self.gridLayout.addWidget(self.lyricsTextEdit, 4, 0, 1, 1)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout.addWidget(self.statusLabel, 5, 0, 1, 1)
        self.serviceComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.serviceComboBox.setObjectName("serviceComboBox")
        self.gridLayout.addWidget(self.serviceComboBox, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spolyrics"))
